Repository hippocrat-dao/hippo-protocol, pull requests merged in 2025-03, with the labels that each got.

#100 fix: v0.50 migration followup
  app/app.go
  app/encoding.go
  app/keepers/keepers.go
  app/params/encoding.go
  app/params/proto.go
  go.mod
  hippod/cmd/init.go
  hippod/cmd/root.go
  hippod/main.go
Labels: help wanted

#101 feat: cosmos-sdk upgrade to v0.50.12
  app/ante.go
  app/app.go
  app/encoding.go
  app/export.go
  app/inflation.go
  app/keepers/keepers.go
  app/keepers/keys.go
  app/params/encoding.go
  app/params/proto.go
  app/upgrades/types.go
  go.mod
  go.sum
  hippod/cmd/genaccounts.go
  hippod/cmd/init.go
  hippod/cmd/root.go
  hippod/main.go
  types/testsuite/suite.go
Labels: help wanted

#117 chore: Add tests for various modules and update dependencies
  app/genesis_test.go
  hippod/cmd/init_test.go
  hippod/cmd/root_test.go
  types/consensus/policy_test.go
  types/consensus/units_test.go
  types/consensus/wallet_test.go
Labels: enhancement

#142 update: add keys in secure way
  README.md
  docs/docs/getting-started/installation.md
Labels: documentation

#144 test: improved genaccounts test coverage
  hippod/cmd/genaccounts_test.go
Labels: enhancement

#146 test: init test cases updates with real cases for improve %
  hippod/cmd/init_test.go
Labels: enhancement
